### ISSUE TITLE
求问demo中admin目录下分别有继承controller和admincontroller的控制器，他们都是admin:make创建的吗？

### ISSUE THREAD

**Issue by ManiuLtd** [z-song/demo.laravel-admin.org#58]
求问demo中admin目录下分别有继承controller和admincontroller的控制器，他们都是admin:make创建的吗？

现在使用admin:make创建的都是继承admincontroller的控制器，请问demo中admin->controller目录下的控制器有的继承的是controller有的是admincontroller，继承controller的控制器是laravel原生命令创建的还是怎么创建的啊？有点迷糊，求老师们指点
![01](https://user-images.githubusercontent.com/36794003/63154840-18545580-c044-11e9-9316-c91027ab155c.png)
![02](https://user-images.githubusercontent.com/36794003/63154852-1be7dc80-c044-11e9-8861-da781db0053f.png)

**Comment by z-song** [comment]
两者都兼容，v1.7.0版本之后改为继承AdminController
